server:
  port: 8888

spring:
  application:
    name: gateway
  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.246:8848,192.168.31.246:8850,192.168.31.246:8852
        namespace: 59f707f4-1c65-406d-bc22-fe6802c5d54b
        username: nacos
        password: nacos
    gateway:
      #设置路由：路由id、路由到微服务的uri、断言
      routes:
        - id: user_route #路由ID，全局唯一，建议配置服务名
          uri: lb://sys-user #lb 整合负载均衡器loadbalancer
          predicates:
            - Path=/user/** # 断言，路径相匹配的进行路由
        - id: role_route
          uri: lb://sys-role
          predicates:
            - Path=/role/**
        - id: inv_route
          uri: lb://biz-inventory
          predicates:
            - Path=/inv/**
        - id: sku_route
          uri: lb://bas-sku
          predicates:
            - Path=/sku/**
        - id: authcenter_route
          uri: lb://authcenter
          predicates:
            - Path=/sku/**
        - id: order_route
          uri: lb://doc-order
          predicates:
            - Path=/order/**
        - id: shopping_cart_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
testnacos:
  gateway:
    shouldSkipUrls:
      - /oauth/**
      - /user/login